name: Deploy Azure Functions

on:
  workflow_dispatch:  
  
env:
  AZURE_FUNCTIONAPP_NAME: skywisejobs
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './WeatherHandler'
  DOTNET_CORE_VERSION: 8.0.x



permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build 
        run: dotnet build ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/WeatherHandler.csproj --configuration Release

      - name: Publish
        run: dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/WeatherHandler.csproj -c Release -o ./myapp

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: function-app
          path: ./myapp
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Development'

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: function-app

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_FA_PUBLISH_PROFILE }}
        
